server:
  port: ${PORT:${SERVER_PORT:8080}}
spring:
  application:
    name: covid19-service
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://localhost:3306/covid19?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:     hikari:      minimum-idle: 10
      idle-timeout: 10000
      maximum-pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate